---
deployment:
  tasks:
    - export DEPLOYPATH=/home/servidorlifem/public_html
    - /bin/find /home/servidorlifem/repositorios/lifemaquinarias -mindepth 1 -maxdepth 1 ! -name ".git" ! -name ".cpanel.yml" ! -name ".htaccess" -exec /bin/cp -Rf {} $DEPLOYPATH/ \;