---
deployment:
  tasks:
    - export REPOPATH=/home/servidorlifem/repositorios/lifemaquinarias
    - export DEPLOYPATH=/home/servidorlifem/public_html
    - /bin/find $REPOPATH -mindepth 1 -maxdepth 1 ! -name ".git" ! -name ".cpanel.yml" ! -name ".htaccess" ! -name ".user.ini" ! -name "php.ini" ! -name "error_log" ! -name "config" -exec /bin/cp -Rf {} $DEPLOYPATH/ \;
    - /bin/find $REPOPATH/config -mindepth 1 -maxdepth 1 ! -name "config.php" -exec /bin/cp -Rf {} $DEPLOYPATH/config/ \;