(() => {
 const config=window.informesMaquirentaConfig,chips=document.getElementById('informeMachineryChips'),panel=document.getElementById('informeDocumentsPanel'),title=document.getElementById('informeSelectedTitle'),tbody=document.getElementById('informeDocumentsBody'),form=document.getElementById('informeDocumentForm');
 const downloadSelectedBtn=document.getElementById('downloadSelectedInformesBtn'),downloadAllBtn=document.getElementById('downloadAllInformesBtn'),dateField=document.getElementById('charlaFecha'),datePreview=document.getElementById('charlaFechaPreview');
 let selectedId=0,selectedName='',rows=[];
 const chipPalette=[['#2563eb','#eff6ff'],['#7c3aed','#f5f3ff'],['#0891b2','#ecfeff'],['#059669','#ecfdf5'],['#d97706','#fffbeb'],['#dc2626','#fef2f2'],['#db2777','#fdf2f8'],['#4f46e5','#eef2ff'],['#0f766e','#f0fdfa'],['#9333ea','#faf5ff']];
 const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
 const displayDate=v=>{if(!v)return '—';const [y,m,d]=String(v).split('-');return `${Number(d)}/${Number(m)}/${y}`};
 const longDate=v=>{if(!v)return 'Seleccione una fecha en el calendario.';const [y,m,d]=v.split('-').map(Number);return `Fecha seleccionada: ${new Intl.DateTimeFormat('es-PE',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date(y,m-1,d))}.`};
 dateField.addEventListener('change',()=>datePreview.textContent=longDate(dateField.value));
 async function request(url,options={}){const response=await fetch(url,{headers:{Accept:'application/json',...(options.headers||{})},...options});const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.message||'No se pudo completar la operación.');return data}
 async function loadMachinery(selectId=0){try{const data=await request(`${config.serviceUrl}?action=list_machinery`);if(!data.rows.length){chips.innerHTML='<span class="text-muted">Todavía no hay maquinarias.</span>';panel.classList.add('d-none');return}chips.innerHTML=data.rows.map((r,index)=>{const colors=chipPalette[index%chipPalette.length];return `<button type="button" class="informes-chip" style="--chip-color:${colors[0]};--chip-soft:${colors[1]}" data-id="${+r.id}" data-name="${esc(r.nombre)}">${esc(r.nombre)}</button>`}).join('');chips.querySelectorAll('.informes-chip').forEach(c=>c.addEventListener('click',()=>selectMachinery(c)));if(selectId)chips.querySelector(`[data-id="${selectId}"]`)?.click()}catch(e){chips.innerHTML=`<span class="text-danger">${esc(e.message)}</span>`}}
 async function selectMachinery(chip){chips.querySelectorAll('.informes-chip').forEach(i=>i.classList.remove('active'));chip.classList.add('active');selectedId=+chip.dataset.id;selectedName=chip.dataset.name;title.textContent=`Charla preoperacional - ${selectedName}`;panel.classList.remove('d-none');await loadDocuments()}
 async function loadDocuments(){tbody.innerHTML='<tr><td colspan="6" class="informes-empty"><span class="spinner-border spinner-border-sm me-2"></span>Cargando...</td></tr>';try{const data=await request(`${config.serviceUrl}?action=list&maquinaria_tipo_id=${selectedId}`);rows=data.rows;renderRows();updateDownloadButtons()}catch(e){tbody.innerHTML=`<tr><td colspan="6" class="informes-empty text-danger">${esc(e.message)}</td></tr>`}}
 function renderRows(){if(!rows.length){tbody.innerHTML='<tr><td colspan="6" class="informes-empty"><i class="fa-regular fa-folder-open"></i>No hay charlas registradas.</td></tr>';return}tbody.innerHTML=rows.map(r=>`<tr><td><input class="form-check-input informe-check" type="checkbox" value="${+r.id}"></td><td>${displayDate(r.fecha)}</td><td>${esc(r.equipo)}</td><td>${r.archivo_path?'<span class="badge bg-success">APTO</span>':'<span class="badge bg-danger">NO APTO</span>'}</td><td>${esc(r.registered_by||'—')}</td><td><div class="informe-row-actions"><button class="btn btn-outline-primary edit-informe" data-id="${+r.id}" title="Editar"><i class="fa-solid fa-pen"></i></button><button class="btn btn-outline-danger delete-informe" data-id="${+r.id}" title="Eliminar"><i class="fa-solid fa-trash"></i></button>${r.archivo_path?`<a class="btn btn-outline-success" href="${config.serviceUrl}?action=file&download=1&id=${+r.id}" title="Descargar adjunto"><i class="fa-solid fa-download"></i></a>`:''}</div></td></tr>`).join('');tbody.querySelectorAll('.edit-informe').forEach(b=>b.addEventListener('click',()=>openModal(+b.dataset.id)));tbody.querySelectorAll('.delete-informe').forEach(b=>b.addEventListener('click',()=>deleteRecord(+b.dataset.id)))}
 function localToday(){const now=new Date();return `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`}
 function openModal(id=0){form.reset();document.getElementById('informeId').value=id||'';document.getElementById('informeMachineryId').value=selectedId;document.getElementById('informeModalTitle').textContent=id?'Editar charla preoperacional':'Agregar documentos';document.getElementById('informeCurrentFile').classList.add('d-none');const r=id?rows.find(x=>+x.id===id):null;dateField.value=r?.fecha||localToday();datePreview.textContent=longDate(dateField.value);document.getElementById('informeObservations').value=r?.observaciones||'';if(r?.archivo_path){const current=document.getElementById('informeCurrentFile');current.innerHTML=`<a class="btn btn-sm btn-outline-primary" href="${config.serviceUrl}?action=file&id=${id}" target="_blank" rel="noopener"><i class="fa-solid fa-eye me-2"></i>Ver archivo actual</a>`;current.classList.remove('d-none')}bootstrap.Modal.getOrCreateInstance(document.getElementById('informeDocumentModal')).show()}
 async function deleteRecord(id){const confirm=await Swal.fire({icon:'warning',title:'¿Eliminar charla?',text:'Esta acción eliminará también el archivo adjunto.',showCancelButton:true,confirmButtonText:'Eliminar',cancelButtonText:'Cancelar',confirmButtonColor:'#dc3545'});if(!confirm.isConfirmed)return;try{const body=new URLSearchParams({action:'delete',csrf_token:config.csrfToken,id});await request(config.serviceUrl,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body});await loadDocuments();Swal.fire({icon:'success',title:'Charla eliminada',timer:1300,showConfirmButton:false})}catch(e){Swal.fire({icon:'error',title:'No se pudo eliminar',text:e.message})}}
 async function downloadArchive(ids=[]){const params=new URLSearchParams({action:'download',maquinaria_tipo_id:String(selectedId)});if(ids.length)params.set('ids',ids.join(','));const button=ids.length?downloadSelectedBtn:downloadAllBtn,original=button.innerHTML;button.disabled=true;button.innerHTML='<span class="spinner-border spinner-border-sm me-2"></span>Preparando...';try{const response=await fetch(`${config.serviceUrl}?${params}`);if(!response.ok){let message='No se pudo preparar la descarga.';try{const error=await response.json();message=error.message||message}catch{}throw new Error(message)}const blob=await response.blob(),disposition=response.headers.get('Content-Disposition')||'',match=disposition.match(/filename="?([^";]+)"?/i),filename=match?.[1]||`Charla_preoperacional_${selectedName}.zip`,url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=filename;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url)}catch(error){Swal.fire({icon:'warning',title:'Descarga no disponible',text:error.message})}finally{button.innerHTML=original;updateDownloadButtons()}}
 function selectedIds(){return [...tbody.querySelectorAll('.informe-check:checked')].map(check=>+check.value)}
 function updateDownloadButtons(){downloadSelectedBtn.disabled=!selectedIds().length;downloadAllBtn.disabled=!rows.some(row=>row.archivo_path)}
 tbody.addEventListener('change',event=>{if(event.target.classList.contains('informe-check'))updateDownloadButtons()});downloadSelectedBtn.addEventListener('click',()=>downloadArchive(selectedIds()));downloadAllBtn.addEventListener('click',()=>downloadArchive());document.getElementById('addInformeDocumentBtn').addEventListener('click',()=>openModal());
 document.getElementById('addInformeMachineryBtn').addEventListener('click',async()=>{const result=await Swal.fire({title:'Agregar maquinaria',input:'text',inputLabel:'Nombre de la maquinaria',inputPlaceholder:'Ejemplo: Excavadora',showCancelButton:true,confirmButtonText:'Agregar',cancelButtonText:'Cancelar',inputValidator:v=>!v.trim()?'Ingrese el nombre de la maquinaria.':undefined});if(!result.isConfirmed)return;try{const body=new URLSearchParams({action:'add_machinery',csrf_token:config.csrfToken,nombre:result.value.trim()});const data=await request(config.serviceUrl,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body});await loadMachinery(+data.id);Swal.fire({icon:'success',title:'Maquinaria agregada',timer:1300,showConfirmButton:false})}catch(e){Swal.fire({icon:'error',title:'No se pudo agregar',text:e.message})}});
 form.addEventListener('submit',async event=>{event.preventDefault();if(!dateField.value){Swal.fire({icon:'warning',title:'Seleccione la fecha de la charla'});return}const button=form.querySelector('[type="submit"]');button.disabled=true;try{await request(config.serviceUrl,{method:'POST',body:new FormData(form)});bootstrap.Modal.getInstance(document.getElementById('informeDocumentModal'))?.hide();await loadDocuments();Swal.fire({icon:'success',title:'Charla guardada',timer:1400,showConfirmButton:false})}catch(error){Swal.fire({icon:'error',title:'No se pudo guardar',text:error.message})}finally{button.disabled=false}});
 loadMachinery();
})();
