let currentMaquirentaSecurityCompanyId=null;
let maquirentaSecurityModal=null;
let maquirentaSecurityReadOnly=false;

document.addEventListener('DOMContentLoaded',()=>{
    const search=document.getElementById('maquirentaSecurityCompanySearch');if(!search)return;
    maquirentaSecurityModal=bootstrap.Modal.getOrCreateInstance(document.getElementById('maquirentaSecurityModal'));
    if(window.jQuery&&$.fn.select2){
        $('#maquirentaSecurityCompanySearch').select2({theme:'bootstrap4',width:'100%',placeholder:'Escriba razón social o RUC'});
        $('#maquirentaSecurityCompanySearch').on('select2:select',event=>loadMaquirentaSecurityCompany(event.params.data.id));
        $('#maquirentaSecuritySelect').select2({theme:'bootstrap4',width:'100%',dropdownParent:$('#maquirentaSecurityModal'),placeholder:'Buscar documento',ajax:{url:`${BASE_URL}/servicios/empresa_maquirenta/seguridad.php?action=catalog`,dataType:'json',delay:200,data:params=>({q:params.term||''})}});
    }
    search.addEventListener('change',event=>{if(event.target.value)loadMaquirentaSecurityCompany(event.target.value);});
    document.getElementById('addMaquirentaSecurityBtn')?.addEventListener('click',openAddMaquirentaSecurity);
    document.getElementById('maquirentaSecurityForm')?.addEventListener('submit',saveMaquirentaSecurity);
    document.getElementById('newMaquirentaSecurityCatalogBtn')?.addEventListener('click',addMaquirentaSecurityCatalog);
    document.getElementById('deleteMaquirentaSecurityCatalogBtn')?.addEventListener('click',deleteMaquirentaSecurityCatalog);
    document.getElementById('downloadMaquirentaSecurityBtn')?.addEventListener('click',()=>downloadMaquirentaSecurity());
    document.getElementById('downloadSelectedMaquirentaSecurityBtn')?.addEventListener('click',downloadSelectedMaquirentaSecurity);
    document.getElementById('changeMaquirentaSecurityPhotoBtn')?.addEventListener('click',()=>document.getElementById('maquirentaSecurityPhotoInput')?.click());
    document.getElementById('maquirentaSecurityPhotoInput')?.addEventListener('change',uploadMaquirentaSecurityPhoto);
});

async function maquirentaSecurityRequest(url,options={}){const response=await fetch(url,options);const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.message||'No se pudo completar la operación.');return data;}
async function maquirentaSecurityPost(action,values){const body=new FormData();body.append('csrf_token',csrf);Object.entries(values).forEach(([key,value])=>body.append(key,value));return maquirentaSecurityRequest(`${BASE_URL}/servicios/empresa_maquirenta/seguridad.php?action=${action}`,{method:'POST',body});}

async function loadMaquirentaSecurityCompany(id){
    try{const data=await maquirentaSecurityRequest(`${BASE_URL}/servicios/empresa_maquirenta/seguridad.php?action=profile&id=${encodeURIComponent(id)}`);const company=data.empresa;currentMaquirentaSecurityCompanyId=String(id);document.getElementById('maquirentaSecurityWorkspace').classList.remove('d-none');document.getElementById('maquirentaSecurityPhoto').src=company.foto_path?`${BASE_URL}/${company.foto_path}`:`${BASE_URL}/recursos/imagen_referencial.php`;document.getElementById('maquirentaSecurityName').textContent=company.razon_social||'';document.getElementById('maquirentaSecurityRuc').textContent=company.ruc||'';document.getElementById('maquirentaSecurityAddress').textContent=company.direccion||'';await loadMaquirentaSecurityRows();}catch(error){Swal.fire('Atención',error.message,'warning');}
}

async function loadMaquirentaSecurityRows(){
    if(!currentMaquirentaSecurityCompanyId)return;const data=await maquirentaSecurityRequest(`${BASE_URL}/servicios/empresa_maquirenta/seguridad.php?action=list&empresa_maquirenta_id=${encodeURIComponent(currentMaquirentaSecurityCompanyId)}&t=${Date.now()}`);const tbody=document.querySelector('#maquirentaSecurityTable tbody');tbody.innerHTML='';
    (data.rows||[]).forEach(row=>{const hasFile=!!row.archivo_path;const download=hasFile?`<a class="btn btn-sm btn-outline-success" href="${BASE_URL}/${row.archivo_path}" download="${escapeHtml(row.archivo_nombre_original||row.documento)}" title="Descargar"><i class="fa-solid fa-download"></i></a>`:'';tbody.insertAdjacentHTML('beforeend',`<tr><td class="text-center"><input class="form-check-input maquirenta-security-check" type="checkbox" value="${row.id}" ${hasFile?'':'disabled'} title="${hasFile?'Seleccionar archivo':'Sin archivo adjunto'}"></td><td>${escapeHtml(row.documento)}</td><td>${row.fecha_registro}</td><td>${row.fecha_inicio}</td><td>${row.fecha_fin}</td><td><span class="badge ${row.status.class}">${row.status.label}</span></td><td>${escapeHtml(row.registered_by||'')}</td><td class="text-nowrap"><button class="btn btn-sm btn-outline-primary" type="button" onclick="openEditMaquirentaSecurity(${row.id})"><i class="fa-solid fa-pen"></i></button><button class="btn btn-sm btn-outline-secondary" type="button" onclick="openViewMaquirentaSecurity(${row.id})"><i class="fa-solid fa-eye"></i></button><button class="btn btn-sm btn-outline-danger" type="button" onclick="deleteMaquirentaSecurity(${row.id})"><i class="fa-solid fa-trash"></i></button>${download}</td></tr>`);});
}

function openAddMaquirentaSecurity(){
    if(!currentMaquirentaSecurityCompanyId)return Swal.fire('Atención','Seleccione una empresa Maquirenta.','warning');maquirentaSecurityReadOnly=false;const form=document.getElementById('maquirentaSecurityForm');form.reset();form.classList.remove('was-validated');setMaquirentaSecurityReadonly(false);document.getElementById('maquirentaSecurityModalTitle').textContent='Agregar documentos';document.getElementById('maquirentaSecurityId').value='';document.getElementById('maquirentaSecurityCompanyId').value=currentMaquirentaSecurityCompanyId;document.getElementById('maquirentaSecurityRegistration').value=localDateValue();$('#maquirentaSecuritySelect').val(null).trigger('change');renderMaquirentaSecurityFile(null);maquirentaSecurityModal.show();
}

async function fillMaquirentaSecurity(id){const data=await maquirentaSecurityRequest(`${BASE_URL}/servicios/empresa_maquirenta/seguridad.php?action=get&id=${id}`);const row=data.row;const form=document.getElementById('maquirentaSecurityForm');form.reset();document.getElementById('maquirentaSecurityId').value=row.id;document.getElementById('maquirentaSecurityCompanyId').value=row.empresa_maquirenta_id;document.getElementById('maquirentaSecurityRegistration').value=row.fecha_registro;document.getElementById('maquirentaSecurityStart').value=row.fecha_inicio;document.getElementById('maquirentaSecurityEnd').value=row.fecha_fin;document.getElementById('maquirentaSecurityObservations').value=row.observaciones||'';$('#maquirentaSecuritySelect').append(new Option(row.documento,row.documento_id,true,true)).trigger('change');renderMaquirentaSecurityFile(row);}
window.openEditMaquirentaSecurity=async id=>{try{maquirentaSecurityReadOnly=false;await fillMaquirentaSecurity(id);setMaquirentaSecurityReadonly(false);document.getElementById('maquirentaSecurityModalTitle').textContent='Editar documentos';maquirentaSecurityModal.show();}catch(error){Swal.fire('Atención',error.message,'warning');}};
window.openViewMaquirentaSecurity=async id=>{try{maquirentaSecurityReadOnly=true;await fillMaquirentaSecurity(id);setMaquirentaSecurityReadonly(true);document.getElementById('maquirentaSecurityModalTitle').textContent='Visualizar documentos';maquirentaSecurityModal.show();}catch(error){Swal.fire('Atención',error.message,'warning');}};

function setMaquirentaSecurityReadonly(state){document.querySelectorAll('#maquirentaSecurityForm input,#maquirentaSecurityForm textarea,#maquirentaSecurityForm select').forEach(element=>{if(element.type!=='hidden')element.disabled=state;});document.querySelector('#maquirentaSecurityForm button[type="submit"]')?.classList.toggle('d-none',state);document.getElementById('newMaquirentaSecurityCatalogBtn')?.classList.toggle('d-none',state);document.getElementById('deleteMaquirentaSecurityCatalogBtn')?.classList.toggle('d-none',state);}
function renderMaquirentaSecurityFile(row){const box=document.getElementById('maquirentaSecurityCurrentFile');if(!row?.archivo_path){box.classList.add('d-none');box.innerHTML='';return;}box.classList.remove('d-none');box.innerHTML=`${documentAttachmentHeader(row)}<div class="d-flex gap-2 mt-2"><a class="btn btn-sm btn-outline-primary" target="_blank" href="${BASE_URL}/${row.archivo_path}"><i class="fa-solid fa-up-right-from-square me-1"></i>Abrir</a><button class="btn btn-sm btn-outline-danger" type="button" onclick="deleteMaquirentaSecurityFile(${row.id})"><i class="fa-solid fa-trash me-1"></i>Eliminar</button></div>`;}

async function saveMaquirentaSecurity(event){event.preventDefault();const form=event.currentTarget;if(maquirentaSecurityReadOnly||!form.checkValidity()){form.classList.add('was-validated');return;}const button=form.querySelector('[type="submit"]');const progress=document.getElementById('maquirentaSecurityProgress');const bar=progress.querySelector('.progress-bar');const label=progress.querySelector('small');button.disabled=true;try{const data=await postFormWithProgress(`${BASE_URL}/servicios/empresa_maquirenta/seguridad.php?action=save`,new FormData(form),percent=>{progress.classList.remove('d-none');bar.style.width=`${percent}%`;label.textContent=percent<100?`Subiendo archivo: ${percent}%`:'Procesando archivo...';});if(!data.ok)throw new Error(data.message||'No se pudo guardar.');maquirentaSecurityModal.hide();await loadMaquirentaSecurityRows();}catch(error){Swal.fire('Atención',error.message,'warning');}finally{button.disabled=false;progress.classList.add('d-none');bar.style.width='0%';}}
window.deleteMaquirentaSecurity=async id=>{if(!await confirmAction('¿Eliminar documento?'))return;try{await maquirentaSecurityPost('delete',{id});await loadMaquirentaSecurityRows();}catch(error){Swal.fire('Atención',error.message,'warning');}};
window.deleteMaquirentaSecurityFile=async id=>{if(!await confirmAction('¿Eliminar archivo adjunto?'))return;try{await maquirentaSecurityPost('delete_file',{id});renderMaquirentaSecurityFile(null);await loadMaquirentaSecurityRows();}catch(error){Swal.fire('Atención',error.message,'warning');}};

async function addMaquirentaSecurityCatalog(){
    const focusTrap=maquirentaSecurityModal?._focustrap;
    focusTrap?.deactivate?.();
    let value='';
    try{
        const result=await Swal.fire({title:'Nuevo documento de seguridad',input:'text',inputPlaceholder:'Nombre del documento',showCancelButton:true,confirmButtonText:'Agregar',cancelButtonText:'Cancelar',didOpen:()=>Swal.getInput()?.focus()});
        value=(result.value||'').trim();
    }finally{
        setTimeout(()=>focusTrap?.activate?.(),0);
    }
    if(!value)return;
    try{const data=await maquirentaSecurityPost('catalog_save',{nombre:value});$('#maquirentaSecuritySelect').append(new Option(data.text,data.id,true,true)).trigger('change');}catch(error){Swal.fire('Atención',error.message,'warning');}
}
async function deleteMaquirentaSecurityCatalog(){const select=$('#maquirentaSecuritySelect');const id=select.val();if(!id)return Swal.fire('Atención','Seleccione un documento para eliminar.','warning');const answer=await Swal.fire({title:'¿Eliminar documento?',text:'Se quitará del catálogo si no tiene registros asociados.',icon:'warning',showCancelButton:true,confirmButtonText:'Sí, eliminar',cancelButtonText:'Cancelar'});if(!answer.isConfirmed)return;try{const data=await maquirentaSecurityPost('catalog_delete',{id});select.find(`option[value="${id}"]`).remove();select.val(null).trigger('change');Swal.fire('Eliminado',data.message,'success');}catch(error){Swal.fire('Atención',error.message,'warning');}}
async function uploadMaquirentaSecurityPhoto(event){const input=event.currentTarget;if(!input.files?.[0]||!currentMaquirentaSecurityCompanyId)return;const body=new FormData();body.append('csrf_token',csrf);body.append('empresa_maquirenta_id',currentMaquirentaSecurityCompanyId);body.append('foto',input.files[0]);try{const data=await maquirentaSecurityRequest(`${BASE_URL}/servicios/empresa_maquirenta/seguridad.php?action=upload_photo`,{method:'POST',body});document.getElementById('maquirentaSecurityPhoto').src=`${data.path}?v=${Date.now()}`;Swal.fire('Actualizado','Foto actualizada.','success');}catch(error){Swal.fire('Atención',error.message,'warning');}finally{input.value='';}}
async function downloadSelectedMaquirentaSecurity(){const ids=Array.from(document.querySelectorAll('.maquirenta-security-check:checked')).map(item=>item.value);if(!ids.length)return Swal.fire('Atención','Seleccione al menos un documento.','warning');await downloadMaquirentaSecurity(ids);}
async function downloadMaquirentaSecurity(ids=[]){if(!currentMaquirentaSecurityCompanyId)return Swal.fire('Atención','Seleccione una empresa Maquirenta.','warning');const params=new URLSearchParams({action:'download',empresa_maquirenta_id:currentMaquirentaSecurityCompanyId});if(ids.length)params.set('ids',ids.join(','));const response=await fetch(`${BASE_URL}/servicios/empresa_maquirenta/seguridad.php?${params}`);if(!response.ok){const data=await response.json().catch(()=>({message:'No se pudo generar la descarga.'}));return Swal.fire('Atención',data.message,'warning');}const blob=await response.blob();const disposition=response.headers.get('Content-Disposition')||'';const match=disposition.match(/filename="([^"]+)"/);const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=match?.[1]||'seguridad_empresa_maquirenta.zip';document.body.appendChild(link);link.click();URL.revokeObjectURL(link.href);link.remove();}
