CREATE TABLE attendance_marks (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    assignment_id INT UNSIGNED NOT NULL,
    worker_id INT UNSIGNED NOT NULL,
    location_id INT UNSIGNED NOT NULL,
    schedule_id INT UNSIGNED NOT NULL,
    mark_type ENUM('entrada','salida') NOT NULL,
    mark_date DATE NOT NULL,
    mark_time TIME NOT NULL,
    marked_at DATETIME NOT NULL,
    latitude DECIMAL(10,8) NOT NULL,
    longitude DECIMAL(11,8) NOT NULL,
    accuracy_meters DECIMAL(10,2) NOT NULL,
    address VARCHAR(255) NULL,
    distance_meters DECIMAL(10,2) NOT NULL,
    within_radius TINYINT(1) NOT NULL DEFAULT 0,
    schedule_status VARCHAR(40) NOT NULL DEFAULT 'pendiente',
    location_status VARCHAR(40) NOT NULL DEFAULT 'pendiente',
    final_status VARCHAR(40) NOT NULL DEFAULT 'pendiente',
    photo_path VARCHAR(255) NULL,
    evidence_path VARCHAR(255) NULL,
    observations TEXT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_attendance_mark_once (worker_id, mark_date, mark_type),
    KEY idx_attendance_marks_worker_date (worker_id, mark_date),
    KEY idx_attendance_marks_assignment (assignment_id),
    KEY idx_attendance_marks_location (location_id),
    CONSTRAINT fk_attendance_mark_assignment FOREIGN KEY (assignment_id) REFERENCES attendance_assignments(id),
    CONSTRAINT fk_attendance_mark_worker FOREIGN KEY (worker_id) REFERENCES workers(id) ON DELETE CASCADE,
    CONSTRAINT fk_attendance_mark_location FOREIGN KEY (location_id) REFERENCES attendance_locations(id),
    CONSTRAINT fk_attendance_mark_schedule FOREIGN KEY (schedule_id) REFERENCES attendance_schedules(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

